[SERVER]
HOST = 0.0.0.0
PORT = 1020

[DATABASE]
# MongoDB connection string with authentication

MONGO_URI = mongodb+srv://nse_scraper_user:J%%40y427512345@nse-scraper-cluster.ljlt3bm.mongodb.net/?appName=nse-scraper-cluster
DATABASE_NAME = NSE_SCRAPER
DB_NAME1 = GETMASTERDATA
COLLECTION_NAME1 = MASTERDATA
MASTERDATA_URI = mongodb+srv://nse_scraper_user:J%%40y427512345@nse-scraper-cluster.ljlt3bm.mongodb.net/
; MASTERDATA_URI = mongodb://sa:963852@192.168.102.120:27017/
MASTERDATA_DB = GETMASTERDATA
FORCE_RUN_JOBS = True

[SCRAPING]
DATA_COLLECTION_INTERVAL = 2
TIMEOUT = 30
COOKIE_REFRESH_INTERVAL = 60

# SQL Server connection details
SQL_SERVER_HOST = 192.168.102.120
SQL_SERVER_DRIVER = ODBC Driver 17 for SQL Server
SQL_SERVER_PORT = 1433
SQL_SERVER_USERNAME = sa
SQL_SERVER_PASSWORD = 963852
SQL_SERVER_DATABASE_NAME = E-IPO
SQL_SERVER_TABLE_NAME = Ipo_Details_master


[PATH]
LOGGER_PATH = Logs


[NSE]
BASE_URL = https://www.nseindia.com
COOKIES_FILE = nse_cookies.json

[FIREBASE]
# Firebase Admin SDK service account JSON file path (relative to project root)
ADMIN_SDK_PATH = firebase-admin-sdk.json

# Enable/disable Firebase authentication
ENABLED = True

# FCM notification settings
FCM_ENABLED = True